version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
    healthcheck:
      test: ["CMD", "psql", "${POSTGRES_DB}", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - starp

  postgres-test:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_PORT=${TEST_POSTGRES_PORT}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    ports:
      - ${TEST_POSTGRES_PORT}:5432
    restart: on-failure
    healthcheck:
      test: ["CMD", "psql", "${TEST_POSTGRES_DB}", "${TEST_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - starp

  app:
    build: .
    restart: "on-failure"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      postgres:
        condition: service_healthy
      postgres-test:
        condition: service_healthy
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TEST_POSTGRES_URL=postgres://${TEST_POSTGRES_USER}:${TEST_POSTGRES_PASSWORD}@postgres-test:5432/${TEST_POSTGRES_DB}
    networks:
      - starp

networks:
  starp:
    driver: bridge
