version: "3.7"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD", "psql", "${POSTGRES_DB}", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: on-failure
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      postgres:
        condition: service_healthy
